# TicketHub — production-style image: Apache + PHP 8.4, document root at public/.
#
#   docker compose up -d           # app on http://localhost:8080
#   docker build -t tickethub .    # image only
#
# The framework itself is vendored in system/, but a small number of optional
# features (SAML sign-in) are real Composer packages, so this build stage
# runs `composer install` into vendor/ and the final stage below copies just
# that directory in — nothing else about the image needs Composer.
FROM composer:2 AS vendor
WORKDIR /app
COPY . .
# --ignore-platform-reqs: the composer:2 image's own PHP is only used to run
# Composer itself here, not the app — the extensions that matter (intl,
# mbstring, ldap, …) are installed into the runtime image below.
RUN composer install --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts --ignore-platform-reqs

FROM php:8.5-apache

# System libraries for the PHP extensions TicketHub uses.
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libicu-dev \
        libonig-dev \
        libpng-dev \
        libjpeg62-turbo-dev \
        libfreetype6-dev \
        libwebp-dev \
        libldap2-dev \
        libzip-dev \
        default-mysql-client \
        unzip \
        ; \
    docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp; \
    docker-php-ext-configure ldap --with-libdir=lib/$(uname -m)-linux-gnu/; \
    docker-php-ext-install -j"$(nproc)" intl mbstring mysqli gd ldap zip opcache; \
    apt-get purge -y --auto-remove libicu-dev libonig-dev libpng-dev libjpeg62-turbo-dev libfreetype6-dev libwebp-dev libldap2-dev libzip-dev; \
    rm -rf /var/lib/apt/lists/*

# Production php.ini plus opcache tuned for a long-running web process.
RUN set -eux; \
    mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"; \
    { \
        echo 'opcache.enable=1'; \
        echo 'opcache.memory_consumption=128'; \
        echo 'opcache.interned_strings_buffer=16'; \
        echo 'opcache.max_accelerated_files=10000'; \
        echo 'opcache.validate_timestamps=0'; \
        echo 'upload_max_filesize=25M'; \
        echo 'post_max_size=26M'; \
        echo 'memory_limit=256M'; \
    } > "$PHP_INI_DIR/conf.d/tickethub.ini"

# Apache: serve public/ only, allow .htaccess rewrites, honour X-Forwarded-* from a proxy.
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN set -eux; \
    a2enmod rewrite headers remoteip; \
    sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf; \
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf; \
    sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf; \
    printf 'ServerTokens Prod\nServerSignature Off\n' > /etc/apache2/conf-available/hardening.conf; \
    a2enconf hardening

WORKDIR /var/www/html

# Application code (see .dockerignore for what stays out) plus the vendor/
# directory built in the composer stage above. Owned by root on purpose: the
# PHP user can read the code but not rewrite it, so a file-write bug cannot
# become code execution. Only writable/ below belongs to www-data.
COPY . /var/www/html
COPY --from=vendor /app/vendor /var/www/html/vendor

# Runtime directories must be writable by the PHP user; .env is generated by the
# entrypoint on first boot when it is not mounted in. The scripts are normalised
# to LF in case the build context came from a Windows checkout.
RUN set -eux; \
    mkdir -p writable/cache writable/logs writable/session writable/uploads writable/debugbar; \
    chown -R www-data:www-data writable; \
    chmod -R ug+rwX writable; \
    sed -i 's/\r$//' docker/entrypoint.sh docker/cron.sh; \
    chmod +x docker/entrypoint.sh docker/cron.sh

ENTRYPOINT ["/var/www/html/docker/entrypoint.sh"]
CMD ["apache2-foreground"]

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
    CMD curl -fsS http://localhost/login >/dev/null || exit 1
