#!/bin/sh
# TicketHub container entrypoint.
#
# 1. Waits for the database to accept connections.
# 2. Writes .env from environment variables when no .env exists (a mounted
#    .env always wins and is never touched).
# 3. Runs pending migrations (php spark migrate --all).
# 4. Hands over to the CMD (apache2-foreground, or the cron loop).
#
# Environment variables (see docker/.env.docker.example):
#   CI_ENVIRONMENT   production | development            (default: production)
#   APP_BASE_URL     public URL with trailing slash      (default: http://localhost:8080/)
#   APP_FORCE_HTTPS  true|false, override HTTPS redirect (default: unset = follow CI_ENVIRONMENT)
#   DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD
#   ENCRYPTION_KEY   hex2bin:... ; generated on first boot when empty
#   SKIP_MIGRATIONS  set to 1 to skip "php spark migrate --all" (e.g. the cron container)
set -eu

cd /var/www/html

CI_ENVIRONMENT="${CI_ENVIRONMENT:-production}"
APP_BASE_URL="${APP_BASE_URL:-http://localhost:8080/}"
DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-tickethub}"
DB_USER="${DB_USER:-tickethub}"
DB_PASSWORD="${DB_PASSWORD:-}"
ENCRYPTION_KEY="${ENCRYPTION_KEY:-}"

log() { printf '[entrypoint] %s\n' "$*"; }

# ---------------------------------------------------------------- wait for DB
wait_for_db() {
    tries=0
    max="${DB_WAIT_SECONDS:-90}"
    log "waiting for database ${DB_HOST}:${DB_PORT} (up to ${max}s)"
    until php -r '
        mysqli_report(MYSQLI_REPORT_OFF);
        $m = mysqli_init();
        $m->options(MYSQLI_OPT_CONNECT_TIMEOUT, 2);
        $ok = @$m->real_connect(getenv("DB_HOST"), getenv("DB_USER"), getenv("DB_PASSWORD"), getenv("DB_NAME"), (int) getenv("DB_PORT"));
        exit($ok ? 0 : 1);
    ' >/dev/null 2>&1; do
        tries=$((tries + 1))
        if [ "$tries" -ge "$max" ]; then
            log "database not reachable after ${max}s — giving up"
            exit 1
        fi
        sleep 1
    done
    log "database is up"
}

# ------------------------------------------------------------------ write .env
write_env() {
    # A real .env mounted by the operator always wins.
    if [ -f .env ] && [ ! -L .env ]; then
        log ".env already present — leaving it alone"
        return
    fi

    # Otherwise the generated file lives on the shared app_writable volume, so
    # it survives container re-creation and the app and cron containers read
    # the SAME file. (Previously each container generated its own, so an
    # unset ENCRYPTION_KEY gave them different keys and cron could not decrypt
    # secrets the app had saved; a re-created container lost its key too.)
    SHARED_ENV=writable/.env
    if [ -f "$SHARED_ENV" ]; then
        ln -sf "$SHARED_ENV" .env
        log "using the shared $SHARED_ENV"
        return
    fi

    if [ -z "$ENCRYPTION_KEY" ]; then
        # key:generate --show prints the key on the last line, e.g. "hex2bin:abcd...".
        ENCRYPTION_KEY="$(php spark key:generate --show 2>/dev/null | grep -o 'hex2bin:[0-9a-f]*' | tail -n 1 || true)"
        if [ -z "$ENCRYPTION_KEY" ]; then
            ENCRYPTION_KEY="hex2bin:$(php -r 'echo bin2hex(random_bytes(32));')"
        fi
        log "generated a new encryption.key (set ENCRYPTION_KEY to keep it stable across rebuilds)"
    fi

    log "writing .env for CI_ENVIRONMENT=${CI_ENVIRONMENT}"
    umask 077
    {
        echo "# Generated by docker/entrypoint.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Mount your own .env to override."
        echo "CI_ENVIRONMENT = ${CI_ENVIRONMENT}"
        echo ""
        echo "app.baseURL = '${APP_BASE_URL}'"
        if [ -n "${APP_FORCE_HTTPS:-}" ]; then
            echo "app.forceGlobalSecureRequests = ${APP_FORCE_HTTPS}"
        fi
        if [ -n "${APP_PROXY_IPS:-}" ]; then
            echo "app.proxyIPs = '${APP_PROXY_IPS}'"
        fi
        echo ""
        echo "database.default.hostname = ${DB_HOST}"
        echo "database.default.port = ${DB_PORT}"
        echo "database.default.database = ${DB_NAME}"
        echo "database.default.username = ${DB_USER}"
        echo "database.default.password = '${DB_PASSWORD}'"
        echo "database.default.DBDriver = MySQLi"
        echo "database.default.charset = utf8mb4"
        echo "database.default.DBCollat = utf8mb4_unicode_ci"
        echo ""
        echo "encryption.key = ${ENCRYPTION_KEY}"
    } > "$SHARED_ENV"
    # Readable by PHP, writable only by root.
    chown root:www-data "$SHARED_ENV"
    chmod 640 "$SHARED_ENV"
    ln -sf "$SHARED_ENV" .env
}

# ------------------------------------------------------------------ migrations
migrate() {
    if [ "${SKIP_MIGRATIONS:-0}" = "1" ]; then
        log "SKIP_MIGRATIONS=1 — not running migrations"
        return
    fi
    log "running migrations"
    php spark migrate --all
}

wait_for_db
write_env
migrate

# writable/ may be a fresh named volume: make sure the runtime dirs exist.
mkdir -p writable/cache writable/logs writable/session writable/uploads writable/debugbar
chown -R www-data:www-data writable
# ...except the shared config, which PHP may read but never rewrite.
if [ -f writable/.env ]; then
    chown root:www-data writable/.env
    chmod 640 writable/.env
fi

log "starting: $*"
exec "$@"
